package:
  name: molsimplify
  version: "1.5.0"

source:
    path: ../

build:
  entry_points:

    - molsimplify = molSimplify.__main__:main

  number: 1

requirements:
  build:
    - python
    - setuptools
    - pytest-runner
  host:
    - pip
    - python
    - pytest-runner
  run:
    - python
    - setuptools
    - openbabel 2.4.1
    - numpy 1.16.4 
    - scikit-learn
    - pandas 
    - keras
    - scipy
    - pyyaml
    - tensorflow 1.14.0
    - hyperopt 0.2.3
    

test:
  # Python imports
  imports:
    - openbabel
  commands:
    - molsimplify -h
  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose


about:
  home: https://github.com/hjkgrp/molSimplify
  summary: "An open source toolkit for discovery of inorganic complexes"

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
