name: CI

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: mols_test
        environment-file: devtools/conda-envs/mols.yml
        python-version: 3.7
        auto-activate-base: false
    - name: Install molSimplify
      run: |
        conda info
        conda list
        pip install -e .
    - name: Run pytest
      run: |
        python setup.py test
    - name: Test command line help message
      run: |
        molsimplify -h