name: CI

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup conda
      uses: s-weigand/setup-conda@v1
      with:
        update-conda: true
    - name: Create environment and install molSimplify
      run: |
        conda env create -n test -f devtools/conda-envs/mols.yml
        conda activate test
        pip install -e .
        conda list
    - name: Run pytest
      run: |
        pytest
    - name: Test command line help message
      run: |
        molsimplify -h