name: CI

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v3
    - name: Conda setup
      uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: devtools/conda-envs/mols.yml
        python-version: 3.7
    - name: Install molSimplify
      run: |
        conda info
        conda list
        pip install -e .
    - name: Run pytest
      run: |
        conda install -c conda-forge pytest pytest-cov
        pytest
    - name: Test command line help message
      run: |
        molsimplify -h