name: CI

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: mols_test
        environment-file: devtools/conda-envs/mols.yml
        python-version: 3.7
    - name: Install molSimplify
      run: |
        pip install -e .
        conda list
    - name: Run pytest
      run: |
        pytest
    - name: Test command line help message
      run: |
        molsimplify -h